/*
	ALGORITMO BÁSICO : CARACTERE TERMINADOR '\0'
	AUTOR : FELIPPE M.
	DESCRIÇÃO : USO DO CARACTERE TERMINADOR DENTRO DE UM LAÇO
*/

#include <stdio.h>
#include <conio.h>
#include <locale.h>
int main()
{
	setlocale(LC_ALL,"PORTUGUESE");		
	char nome[50] = "FELIPPE MARQUES DA SILVA DE ALMEIDA AHIRE";
	int i;
	
	/*
		'\0' = É O TERMINADOR DA STRING. INDICA QUE A LEITURA DE CARACTERE TERMINOU
	*/
	
	for(i=0;nome[i] != '\0';i++){
	/*
		'\0' = É O TERMINADOR DA STRING. INDICA QUE A LEITURA DE UMA VARIÁVEL CHAR TERMINOU;
		OU SEJA, O LAÇO DE REPEITAÇÃO SERÁ EXECUTADO ATÉ O TERMONADOR SER ENCONTRADO (QUE É O ÚLTIMO CARACTERE (E)).
		O INTERESSANTE É QUE NÃO É NECESSÁRIO PERCORRER AS 50 POSIÇÕES, MAS SIM ATÉ O ÚLTMA CARACTERE.
	*/	
		printf("LETRA [%i]: %c \n",i,nome[i]);
	}
	  
}
